"""empty message

Revision ID: 5e5eeb2b65f1
Revises: 7b26798291e0
Create Date: 2024-12-23 20:50:58.846275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5eeb2b65f1'
down_revision = '7b26798291e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idTransaction', sa.Integer(), nullable=False),
    sa.Column('idProduct', sa.Integer(), nullable=False),
    sa.Column('productAmount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProduct'], ['product.id'], ),
    sa.ForeignKeyConstraint(['idTransaction'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_product')
    # ### end Alembic commands ###
